name: draw_on_image_plugin
description: Flutter plugin for drawing text on images.
version: 1.0.0
repository: https://github.com/Nikolaiko/DrawOnImagePlugin

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.23.0-0"

dependencies:
  flutter:
    sdk: flutter    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nikolai.imagedraw.draw_on_image_plugin
        pluginClass: DrawOnImagePlugin
      ios:
        pluginClass: DrawOnImagePlugin